### ISSUE TITLE
tracking object

### ISSUE THREAD

**Issue by Mirshal** [naseemap47/streamlit-yolov7#19]
whether you can insert tracking codes such as strong sort, or deep sort into the detection object?
thanks for your help

**Comment by naseemap47** [comment]
Hi @Mirshal,
Sure I can do that. Once its done, I will update you.

**Comment by Mirshal** [comment]
thanks for help


Pada Min, 22 Sep 2024 pukul 10.56 NASEEM A P ***@***.***>
menulis:

**Comment by naseemap47** [comment]
@Mirshal Thanks for using this repo.
If any issues are there please let me know.
